/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormAritmeticas.java
 *
 * Created on 01-dic-2008, 14:03:49
 */

package basics.ui;

import basics.classes.Aritmeticas;

/**
 *
 * @author Administrador
 */
public class FormAritmeticas extends javax.swing.JFrame {

    /** Creates new form FormAritmeticas */
    public FormAritmeticas() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG1 = new javax.swing.ButtonGroup();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        RadioSumar = new javax.swing.JRadioButton();
        RadioRestar = new javax.swing.JRadioButton();
        RadioMultiplicar = new javax.swing.JRadioButton();
        RadioDividir = new javax.swing.JRadioButton();
        lbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Operaciones Aritméticas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("=");

        BG1.add(RadioSumar);
        RadioSumar.setText("Sumar");
        RadioSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioSumarActionPerformed(evt);
            }
        });

        BG1.add(RadioRestar);
        RadioRestar.setText("Restar");
        RadioRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioRestarActionPerformed(evt);
            }
        });

        BG1.add(RadioMultiplicar);
        RadioMultiplicar.setText("Multiplicar");
        RadioMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioMultiplicarActionPerformed(evt);
            }
        });

        BG1.add(RadioDividir);
        RadioDividir.setText("Dividir");
        RadioDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioDividirActionPerformed(evt);
            }
        });

        lbl1.setText("?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioRestar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioDividir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioSumar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RadioMultiplicar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioSumar)
                            .addComponent(RadioMultiplicar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioRestar)
                            .addComponent(RadioDividir)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
Aritmeticas obj = new Aritmeticas();
    private void RadioSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioSumarActionPerformed
        // TODO add your handling code here:
        if(RadioSumar.isSelected()){
            lbl1.setText("+");
        }
}//GEN-LAST:event_RadioSumarActionPerformed

    private void RadioRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioRestarActionPerformed
        // TODO add your handling code here:
        if(RadioRestar.isSelected()){
            lbl1.setText("-");
        }
    }//GEN-LAST:event_RadioRestarActionPerformed

    private void RadioMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioMultiplicarActionPerformed
        // TODO add your handling code here:
        if(RadioMultiplicar.isSelected()){
            lbl1.setText("x");
        }
    }//GEN-LAST:event_RadioMultiplicarActionPerformed

    private void RadioDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioDividirActionPerformed
        // TODO add your handling code here:
        if(RadioDividir.isSelected()){
            lbl1.setText("/");
        }
    }//GEN-LAST:event_RadioDividirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if(RadioSumar.isSelected()){
                txt3.setText(""+obj.Suma(Double.parseDouble(txt1.getText()), Double.parseDouble(txt2.getText())));
            } else if(RadioRestar.isSelected()){
                txt3.setText(""+obj.Resta(Double.parseDouble(txt1.getText()), Double.parseDouble(txt2.getText())));
            } else if(RadioMultiplicar.isSelected()){
                txt3.setText(""+obj.Multiplicacion(Double.parseDouble(txt1.getText()), Double.parseDouble(txt2.getText())));
            } else if(RadioDividir.isSelected()){
                txt3.setText(""+obj.Division(Double.parseDouble(txt1.getText()), Double.parseDouble(txt2.getText())));
            }
        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, "Sólo puede ingresar números");
            txt1.setText("");
            txt2.setText("");
            txt3.setText("");
            txt1.requestFocus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BG1;
    private javax.swing.JRadioButton RadioDividir;
    private javax.swing.JRadioButton RadioMultiplicar;
    private javax.swing.JRadioButton RadioRestar;
    private javax.swing.JRadioButton RadioSumar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    // End of variables declaration//GEN-END:variables

}
