/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on 01-dic-2008, 13:56:06
 */

package basics.ui;

/**
 *
 * @author Administrador
 */
public class Main extends javax.swing.JFrame {

    /** Creates new form FormPrincipal */
    public Main() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        Marchivo = new javax.swing.JMenu();
        Moperaciones = new javax.swing.JMenu();
        aritmeticas = new javax.swing.JMenuItem();
        algebraicas = new javax.swing.JMenuItem();
        Mextras = new javax.swing.JMenu();
        primos = new javax.swing.JMenuItem();
        capicua = new javax.swing.JMenuItem();
        bisiesto = new javax.swing.JMenuItem();
        separador = new javax.swing.JSeparator();
        Salir = new javax.swing.JMenuItem();
        Mayuda = new javax.swing.JMenu();
        Mabout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Básico");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basics/images/fondito.jpg"))); // NOI18N

        Marchivo.setMnemonic('A');
        Marchivo.setText("Archivo");

        Moperaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basics/images/flecha.png"))); // NOI18N
        Moperaciones.setText("Operaciones Básicas");

        aritmeticas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aritmeticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basics/images/aritmeticas.png"))); // NOI18N
        aritmeticas.setText("Aritméticas");
        aritmeticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aritmeticasActionPerformed(evt);
            }
        });
        Moperaciones.add(aritmeticas);

        algebraicas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        algebraicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basics/images/algebraicas.png"))); // NOI18N
        algebraicas.setText("Algebráicas");
        algebraicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algebraicasActionPerformed(evt);
            }
        });
        Moperaciones.add(algebraicas);

        Marchivo.add(Moperaciones);

        Mextras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basics/images/flecha.png"))); // NOI18N
        Mextras.setText("Extras");

        primos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        primos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basics/images/primos.png"))); // NOI18N
        primos.setText("Números Primos");
        primos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primosActionPerformed(evt);
            }
        });
        Mextras.add(primos);

        capicua.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        capicua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basics/images/capicua.png"))); // NOI18N
        capicua.setText("Números Capicua");
        capicua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capicuaActionPerformed(evt);
            }
        });
        Mextras.add(capicua);

        bisiesto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        bisiesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basics/images/bisiesto.png"))); // NOI18N
        bisiesto.setText("Año Bisiesto");
        bisiesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bisiestoActionPerformed(evt);
            }
        });
        Mextras.add(bisiesto);

        Marchivo.add(Mextras);
        Marchivo.add(separador);

        Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basics/images/exit.png"))); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Marchivo.add(Salir);

        BarraMenu.add(Marchivo);

        Mayuda.setMnemonic('y');
        Mayuda.setText("Ayuda");

        Mabout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        Mabout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basics/images/about.png"))); // NOI18N
        Mabout.setText("Acerca de...");
        Mabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaboutActionPerformed(evt);
            }
        });
        Mayuda.add(Mabout);

        BarraMenu.add(Mayuda);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aritmeticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aritmeticasActionPerformed
        // TODO add your handling code here:
        new FormAritmeticas().setVisible(true);
    }//GEN-LAST:event_aritmeticasActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void MaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaboutActionPerformed
        // TODO add your handling code here:
        new FormAbout().setVisible(true);
    }//GEN-LAST:event_MaboutActionPerformed

    private void algebraicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algebraicasActionPerformed
        // TODO add your handling code here:
        new FormAlgebraicas().setVisible(true);
    }//GEN-LAST:event_algebraicasActionPerformed

    private void capicuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capicuaActionPerformed
        // TODO add your handling code here:
        new FormCapicua().setVisible(true);
    }//GEN-LAST:event_capicuaActionPerformed

    private void primosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primosActionPerformed
        // TODO add your handling code here:
        new FormPrimos().setVisible(true);
}//GEN-LAST:event_primosActionPerformed

    private void bisiestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bisiestoActionPerformed
        // TODO add your handling code here:
        new FormBisiesto().setVisible(true);
    }//GEN-LAST:event_bisiestoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem Mabout;
    private javax.swing.JMenu Marchivo;
    private javax.swing.JMenu Mayuda;
    private javax.swing.JMenu Mextras;
    private javax.swing.JMenu Moperaciones;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem algebraicas;
    private javax.swing.JMenuItem aritmeticas;
    private javax.swing.JMenuItem bisiesto;
    private javax.swing.JMenuItem capicua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem primos;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables

}
